### ISSUE TITLE
Example Robot scripts not working on a different Model.

### ISSUE THREAD

**Issue by abhijeet-sridhar** [EricVoll/RobotDynamicsLibrary#5]
Hey, I was trying out the RobotDynamics in Unity, and I tried attaching the Robot script given in the example folder for FANUC to my own model. I made the changes for setting up the robot using AddJoints functions. Yet the model was not moving at all. On further debugging, i found that result.DidConverge was always false, no matter where i move the target. 

Also to point out, the example FANUC is scaled up to 30 times and the AddJoints() vector is made based on the scaled up model. Does this effect the result and should I try scaling up my model to try this?

**Comment by EricVoll** [comment]
Hi @adhijeet-sridhar 
could you share the repo of your attempt?
Then I could take a quick look :) Its a bit hard to find the problem without seeing it myself.

**Comment by abhijeet-sridhar** [comment]
Hi, sorry for the late response, but because of my company policies, i cannot share the full repo, I will include the details i did for setup here and see if that could help.

I created a new robot, and assigned the joints this way: 

```
public class myRobot : Robots.Robot
    {
        public myRobot() => this.Links = new Robots.Robot()
            .AddJoint('y', new Vector(1.052113, 0.8570129, 1.150335))
            .AddJoint('y', new Vector(0.0, 0.4727451, 0.206797))
            .AddJoint('y', new Vector(0.0, -0.052354, -0.209469)).Links;
    }
```


Then I took the robot script from the example unity project (https://github.com/EricVoll/RobotDynamicsLibrary/blob/master/UnityExamples/RobotKinematics/Assets/RobotDynamics/Robot.cs) and replaced the Fanuc by myRobot. 

I then attached the target and the joints from the unity inspector tab. 

Is there any more setup needed here?

**Comment by EricVoll** [comment]
ok sure no problem.
It looks like your robot only contains joints that rotate around the y-axis, and has only 3 DOF. This means, that the target poses, that your robot can reach, can only lie in the x-z-plane. 
So an assumption would be, that your target poses that you give it to calculate the inverse kinematics of, are simply not reachable for that specific robot. 
You could test that by doing the following:
- Assume some (random or not random) angles for each joint
- Do the forward kinematics (also contained in the library) and write down the end-effectors pose.
- Feed this end-effector pose into the inverse-kinematics to see if it converges (which it should, because by definition this pose is reachable by your robot)

Also, i only ever tested this repo's code on 6+ DOF robots... I am not sure how well it handles robots with fewer joints.

**Comment by abhijeet-sridhar** [comment]
I'll clarify here that the Robot has an ability to go up and down with a separate translationary joint but since linear transformations are not calculated, I thought there's no need to add that joint in the constructor. I plan to handle this joint separately since it just needs to go up or down regardless of the angles of other joints. Is that a problem? 

I will try whether the end effector pose converges and get back :)

**Comment by EricVoll** [comment]
Well that is not a problem, if you substract the offset in that direction before passing it to the inverse kinematics. The pose that the inverse kinematics can reach, has to have a 1,27... in the y-component (which is the sum of offsets of your joints in the y-axis). That makes sense because your robot (as defined in the code - the inverse kinematics part doesn't "know" of you additional translational joint) cannot change the y-value of the endeffector in any way, since it has no DOF in that axis. :)

**Comment by EricVoll** [comment]
Also play around (increase) with the tolerance values. Since your robot cannot change the y-value, a tolerance of zero might never be reached in any case.

**Comment by abhijeet-sridhar** [comment]
Hey @EricVoll, I tried this sample code to calculate forward kinematics and pass the end effector pose to the inverse kinematics - 
```
private void RandomFunction()
    {
        var result = CRobot.ComputeForwardKinematics(new double[] { 90, 0, 0 });
        HomogenousTransformation homogenousTransformation = result[result.Count-1];
        var result2 = CRobot.ComputeInverseKinematics(homogenousTransformation.GetPosition(), homogenousTransformation.GetRotation(), Lambda, Alpha, MaxIter);
        Debug.Log("converged: " + result2.DidConverge);
    }
```
With this, I'm rotating just the first joint by 90, getting the last homogenous transformation, and trying to compute inverse kinematics with the result. Here, the Log prints true, indicating that the transformation did converge, but the joints of my robot just vanish and go to some random position.

**Comment by abhijeet-sridhar** [comment]
Also just asking, the tolerance is specified in the variable Kp or alpha?

**Comment by EricVoll** [comment]
The method `[ComputeInverseKinematics(...)](https://github.com/EricVoll/RobotDynamicsLibrary/blob/853edc1c4dfe33785a824caa3a420bda71c52793/RobotDynamics/RobotDynamics/Robots/Robot.cs#L58)" has an additional paramter called "tol", which is set to 0.1 initially. You can increase that.

Your demo-code looks fine. I'll replicate your setup today and test it. :)

**Comment by EricVoll** [comment]
Just FYI:
`Kp`: Is the gain value for the P-controller that smooths the movements. It has no influence on the convergence behaviour of the algorithm.
`lambda`: Is a value which is added to the main-diagonals in matrices when calculating the pseudo-inverses of them. This makes everything a bit more stable in near-to-singularity positions.
`alpha`: Is a step-size parameter. Increasing it makes the algorithm faster, but might lead to it skipping the solution and bouncing around for longer.

**Comment by abhijeet-sridhar** [comment]
Hey, I just put together a minimal working example project which I'm attaching here. This replicates my issue of joints going to random positions. Just press play on the sample scene and the joints go up.
 
[KinematicsSample.zip](https://github.com/EricVoll/RobotDynamicsLibrary/files/5988219/KinematicsSample.zip)

**Comment by EricVoll** [comment]
ok I found the problem.
There were two issues with your setup. In the HomogenousCoordinate-Transforms (The coordinates/axes you define when setting up the links) you have to specify the next rotation-axe relative to the previous rotation axe. So you coordinates were a bit off. They should be:
```
            this.Links = new Robots.Robot()
            .AddJoint('y', new Vector(0, 0.03293461, 0))
            .AddJoint('y', new Vector(-0.2241943, 0.4691764, 0))
            .AddJoint('y', new Vector(0.1998537, -0.05284593, 0)).Links;
```

Second: The script places the joints relative to the Robot-Base, not to the previous joint. So the joints have to be "flattened" in the hierarchy like so:
![image](https://user-images.githubusercontent.com/28082576/108075204-621f6100-706a-11eb-9e27-30a547c2b722.png)

Here is the fixed version of your code 🙂

By the way: The default value for the tolerance of 0.1 is fine in the Fanuc robot case, since the other values are in the range of ~500. In your case 0.1 is a bit of a large tolerance, since its about 10% of the whole range of motion. I set it to 0.01f (or even smaller) and now it looks nice and is precise :)

In the meantime I also added the option to let the algorithm initialize with the previous joint angles. That removes the jittering if multiple solutions are available and also speeds up the whole thing :) . This zip already contains the new dll. 
[KinematicsSample.zip](https://github.com/EricVoll/RobotDynamicsLibrary/files/5991272/KinematicsSample.zip)

**Comment by EricVoll** [comment]
Feel free to close the issue if your problems are solved

**Comment by abhijeet-sridhar** [comment]
Hi, thanks for that amazing solution. The algorithm works like a charm. I will go ahead and close this issue. 

I was wondering how would I go about slowing down the joint movements. If for example, i move the target to a location and run the algorithm on a key press event, all the joints come to the correct position in milliseconds. Is there a way we could slow out the motion of these joints so that we can actually see them moving.

**Comment by EricVoll** [comment]
oh thats easy. The default app shows you how to use a P-Controller (which is already in the library), and can be activated in the inspector "Use Controller" (or something similar) 
The zip I sent you also contains the controller implemented - just not activated by default. You might have to play around (reduce) with the Kp value, since it is tuned to the Fanuc example, where all values are about 100 times larger than in your case.

**Comment by abhijeet-sridhar** [comment]
Just tried it, everything works perfect. Is there a way we could check whether a given position is in the range of the robot? If I compute inverse kinematics and check result.DidConverge, I think it sets the init position as the farthest the robot can reach. The next time I try to change the target position and move, it starts from that initial position. I tried setting UseLastQAsInitValue to false but I dont think that affects this behaviour.

**Comment by EricVoll** [comment]
Well you should be able to just call the InverseKinematics and then Check "DidConverge". DidConverge is false if the numeric algorithms fails to converge within the given number of iterations. So either the pose is not reachable, or the allowed number of iterations is too low (in combination with the step size alpha etc.)

You don't have to set the joint values after checking "DidConverge"

**Comment by abhijeet-sridhar** [comment]
Okay, I think I'm good for now :) Thanks a bunch for the help. I'll comment if I have any more doubts.

**Comment by abhijeet-sridhar** [comment]
Hey, is there any way we could feed the values to the AddJoints programatically? This would be useful in a case where the Robot's initial location is not fixed. I was thinking along these lines:

```
public class myRobot : Robots.Robot
    {
        public myRobot(List<GameObject> joints)
        {
            this.Links = new Robots.Robot()
                .AddJoint('y',
                    new Vector(
                        joints[0].transform.position.x, 
                        joints[0].transform.position.y,
                        joints[0].transform.position.z))
                .AddJoint('y', new Vector(
                    joints[1].transform.position.x-joints[0].transform.position.x,
                    joints[1].transform.position.y-joints[0].transform.position.y,
                    joints[1].transform.position.z-joints[0].transform.position.z))
                .AddJoint('y', new Vector(
                    joints[2].transform.position.x-joints[1].transform.position.x,
                    joints[2].transform.position.y-joints[1].transform.position.y,
                    joints[2].transform.position.z-joints[1].transform.position.z)).Links;
        }
    }
```

**Comment by EricVoll** [comment]
Could you please create a new issue for that?
(Better for overview etc.)
