### ISSUE TITLE
Assigning the parameters for Robot initialisation programatically.

### ISSUE THREAD

**Issue by abhijeet-sridhar** [EricVoll/RobotDynamicsLibrary#6]
Hi, while initialising the vector coordinates for Linking the robot, can the values to AddJoint method be given programatically?
This would be useful in a case where the Robot's initial location is not fixed. I was thinking along these lines:
```
public class myRobot : Robots.Robot
    {
        public myRobot(List<GameObject> joints)
        {
            this.Links = new Robots.Robot()
                .AddJoint('y',
                    new Vector(
                        joints[0].transform.position.x, 
                        joints[0].transform.position.y,
                        joints[0].transform.position.z))
                .AddJoint('y', new Vector(
                    joints[1].transform.position.x-joints[0].transform.position.x,
                    joints[1].transform.position.y-joints[0].transform.position.y,
                    joints[1].transform.position.z-joints[0].transform.position.z))
                .AddJoint('y', new Vector(
                    joints[2].transform.position.x-joints[1].transform.position.x,
                    joints[2].transform.position.y-joints[1].transform.position.y,
                    joints[2].transform.position.z-joints[1].transform.position.z)).Links;
        }
    }
```

**Comment by EricVoll** [comment]
I would do it (and did it) differently:
Before calling the inverse kinematics, transform the target pose into the local coordinate system of your robot (which can be done with [Unity-Methods](https://docs.unity3d.com/ScriptReference/Transform.InverseTransformPoint.html). This way you can keep the numbers constant in your robot definition, but still have it moving around and the target object doesn't have to be a hierarchical child of the robot.


If you do what you suggested, the kinematic structure looks different. Because the first Link will go from (0,0,0) to the position of the first joint, which is a completely different kinematic structure. This could be solved if the library supported static / non-moveable joints, but it doesn't.
I'd go with the option described above, which is also more general and better maintainable.

**Comment by abhijeet-sridhar** [comment]
Hey, I have a linear joint which changes the distances between joints used here. How can I handle this? I thought of making the constructor programatic but still we wouldn't be able to change it in runtime right?

**Comment by EricVoll** [comment]
While the mathematical framework supports linear joints, my implementation of the sovler doesn't... Maybe I have time in future to look at that, but currently I don't have enough time...

**Comment by EricVoll** [comment]
@abhijeet-sridhar I added support for linear joints today :)

**Comment by abhijeet-sridhar** [comment]
Will check it out :)

**Comment by abhijeet-sridhar** [comment]
Hey, the Unity example seems to have some problem in it? The prefab for the mixed robot had a plane attached to it and some of the joints weren't visible. Can you check it once?

**Comment by EricVoll** [comment]
Yeah the plane was just there to show where the "0" y-value is. The robot "joints" aren't modelled really. I just attached a few cylinders in a sequence and did not care if the joints mechanically makes sense ^^
The math works and is usable with your modell as well.

**Comment by abhijeet-sridhar** [comment]
Ah got it. I'll try it with my model and see how it goes :)
